[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py flush --noinput && python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py shell -c \"from accounts.models import User; User.objects.create_superuser('admin', '', 'admin123!', role='admin') if not User.objects.filter(username='admin').exists() else print('exists')\" && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
